### ISSUE TITLE
Select the version of qtifw tool to download

### ISSUE THREAD

**Issue by batcaveMessi** [ddalcino/aqt-list-server#38]
I am using github actions to get the qt and its ifw tools using below actions
`      - name: Install qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{ github.workspace }}/qt/'
          cache: 'true'
          aqtversion: '==3.1.*'
          version: ${{ inputs.qt_version }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qt3d qt5compat qtwebview qtshadertools'
          archives: 'qttranslations qttools qtsvg qtdeclarative qtbase d3dcompiler_47'
          tools: 'tools_ifw'
`
This worked totally fine until couple of weeks ago. QT updated the ifw version to 4.7 from 4.6 and I had the 4.6 as hardcoded path in my system. Since the update, action downloaded 4.7 and due to this mismatch builds started failing. 

I wanted to ask if its possible to specify the ifw version as well in the action itself so that we know which version of IFW is installed on the system?

**Comment by ddalcino** [comment]
This issue is already tracked in aqtinstall here:

https://github.com/miurahr/aqtinstall/issues/693

**Comment by pzhlkj6612** [comment]
Hi.

> if its possible to specify the ifw version as well in the action itself so that we know which version of IFW is installed on the system?

The ifw version is controlled by Qt and there is only one version of ifw on their site, so I think it's impossible to specify the version number. In addition, Qt guys may even modify the file structure [1], so only relying on a version number is not such reliable.

[1] in the archive `https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_ifw/qt.tools.ifw.XXX/XXXifw-win-x86.7z`

Btw, you can format your YAML file with the \`\`\` block ([Creating and highlighting code blocks § Creating and highlighting code blocks - GitHub Docs](https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)).

**Comment by batcaveMessi** [comment]
> Hi.
> 
> > if its possible to specify the ifw version as well in the action itself so that we know which version of IFW is installed on the system?
> 
> The ifw version is controlled by Qt and there is only one version of ifw on their site, so I think it's impossible to specify the version number. In addition, Qt guys may even modify the file structure [1], so only relying on a version number is not such reliable.
> 
> [1] in the archive `https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_ifw/qt.tools.ifw.XXX/XXXifw-win-x86.7z`
> 
> Btw, you can format your YAML file with the ``` block ([Creating and highlighting code blocks § Creating and highlighting code blocks - GitHub Docs](https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)).

The last time I checked - which was 2 weeks ago - they still had 4.6,  that is why I wanted to specify the ifw version just like the way we specify qt version.

**Comment by ddalcino** [comment]
The Qt repo maintainers update the tool versions automatically, whenever they have a new version ready, and they remove the old one. If your CI action uses a path to one of the IFW tools, and that path includes a version number like '4.6', you'll need to change that number to a glob star (`*`) if you don't want your action to break every few months.

**Comment by batcaveMessi** [comment]
https://download.qt.io/official_releases/qt-installer-framework/ I found both 4.6 and 4.7 here

I see that the URLs are different. I am not sure what is the idea behind it but it is rather confusing when IFW can be downloaded from 2 different URLs.
