### ISSUE TITLE
Outdated qt-repo-cache since Jun 13, 2024

### ISSUE THREAD

**Issue by pzhlkj6612** [ddalcino/aqt-list-server#44]
Hey! Qt 6.7.2 has been already released [^1] but I can't find it on the website. The cache updater [^2] has not been working since `Jun 13, 2024, 12:54 AM UTC`.

[^1]: https://www.qt.io/blog/qt-6.7.2-released
[^2]: https://github.com/ddalcino/qt-repo-cache/actions

**Comment by ddalcino** [comment]
Should be fixed now. It doesn't show Qt 6.7.3 yet because of https://github.com/miurahr/aqtinstall/issues/817, but aqtinstall isn't yet capable of installing that one yet anyway.

**Comment by pzhlkj6612** [comment]
Thank you! I can find Qt 6.7.2 for Linux and macOS. For now, only Windows doesn't have the new version.
